layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 12
  exclude:
    archived: false
    forks: false
    projects:
      - pub-yes
      - yest
      - archive-crypto
      - yest-the-docs
      - bahamas-crypto
      - "404"
      - about-cryptography
      - learn-python
      - webpage-webmentions
      - rwot3-sf
      - rwot1-sf
      - rwot2-id2020
      - google-sheet-to-github-website
      - identity-commons
      - neo-hpstr-jekyll-theme

social_media:
  website: https://infominer.id/
  keybase: infominer
  telegram: infominer33
  twitter: infominer33
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # unsplash: your_username
  # vk: your_username
  # youtube: your_username

topics:
  - name: Bitcoin
    web_url: https://github.com/topics/bitcoin
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/bitcoin/bitcoin.png

  - name: Decentralized Identity
    web_url: https://github.com/topics/decentralized-identity
    image_url: https://infominer.id/DIDecentralized/assets/icons/didicon.png

  - name: Linux
    web_url: https://github.com/topics/linux
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/linux/linux.png

  - name: Jekyll
    web_url: https://github.com/topics/jekyll
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/jekyll/jekyll.png

  - name: P2P
    web_url: https://github.com/topics/p2p
    image_url: https://infominer.id/github-portfolio/assets/peer-to-peer.png
  
  - name: Publishing
    web_url: https://github.com/topics/publishing
    image_url: https://infominer.id/github-portfolio/assets/publishing.png
    
  